In [2]:
import numpy as np

In [3]:
ones=np.ones((3,3))

In [6]:
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
zeroes=np.zeros((5,5))

In [10]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
aarr=np.arange(1,10,3)

In [14]:
aarr

array([1, 4, 7])

In [21]:
rana=np.random.randint(1,100,(2,3))

In [22]:
rana

array([[93, 63, 46],
       [42, 88, 47]])

In [24]:
rana.dtype

dtype('int64')

In [25]:
type(rana)

numpy.ndarray

In [27]:
rana.size

6