In [1]:
import numpy as np

In [5]:
mat1=np.random.randint(10,size=(3,5))

In [10]:
mat2=np.random.randint(100,size=(3,6))

In [11]:
mat1

array([[3, 8, 5, 1, 2],
       [9, 4, 2, 3, 3],
       [0, 7, 2, 4, 4]])

In [12]:
mat2

array([[86, 64,  3, 67, 31, 79],
       [67, 90, 94, 34, 89, 79],
       [10, 73, 17, 69, 56,  3]])

In [25]:
max=np.reshape(mat1,(5,3,1))

In [26]:
max

array([[[3],
        [8],
        [5]],

       [[1],
        [2],
        [9]],

       [[4],
        [2],
        [3]],

       [[3],
        [0],
        [7]],

       [[2],
        [4],
        [4]]])

In [27]:
mat2*max

array([[[258, 192,   9, 201,  93, 237],
        [536, 720, 752, 272, 712, 632],
        [ 50, 365,  85, 345, 280,  15]],

       [[ 86,  64,   3,  67,  31,  79],
        [134, 180, 188,  68, 178, 158],
        [ 90, 657, 153, 621, 504,  27]],

       [[344, 256,  12, 268, 124, 316],
        [134, 180, 188,  68, 178, 158],
        [ 30, 219,  51, 207, 168,   9]],

       [[258, 192,   9, 201,  93, 237],
        [  0,   0,   0,   0,   0,   0],
        [ 70, 511, 119, 483, 392,  21]],

       [[172, 128,   6, 134,  62, 158],
        [268, 360, 376, 136, 356, 316],
        [ 40, 292,  68, 276, 224,  12]]])

In [28]:
mat1T=mat1.T

In [30]:
mat1T

array([[3, 9, 0],
       [8, 4, 7],
       [5, 2, 2],
       [1, 3, 4],
       [2, 3, 4]])

In [31]:
np.dot(mat1T,mat2)

array([[ 861, 1002,  855,  507,  894,  948],
       [1026, 1383,  519, 1155,  996,  969],
       [ 584,  646,  237,  541,  445,  559],
       [ 327,  626,  353,  445,  522,  328],
       [ 413,  690,  356,  512,  553,  407]])

In [32]:
max.T

array([[[3, 1, 4, 3, 2],
        [8, 2, 2, 0, 4],
        [5, 9, 3, 7, 4]]])