# Manipulating arrays

In [2]:
import numpy as np

In [3]:
a1=np.array([2,3,5])

In [4]:
a1

array([2, 3, 5])

In [15]:
a2=np.random.randint(10,15,(1,3))

In [16]:
a2

array([[11, 12, 10]])

In [17]:
a1+a2

array([[13, 15, 15]])

In [18]:
%run "Numpy intro.ipynb"

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a2

array([[1, 3, 5],
       [2, 4, 6]])

In [21]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [22]:
a2.shape

(2, 3)

In [23]:
a3.shape

(2, 3, 3)

In [33]:
a3=np.reshape(a3,(3,2,3))

In [34]:
a2

array([[1, 3, 5],
       [2, 4, 6]])

In [36]:
ax=a2*a3

In [37]:
ax

array([[[  1,   6,  15],
        [  8,  20,  36]],

       [[  7,  24,  45],
        [ 20,  44,  72]],

       [[ 13,  42,  75],
        [ 32,  68, 108]]])

In [38]:
ax+ax

array([[[  2,  12,  30],
        [ 16,  40,  72]],

       [[ 14,  48,  90],
        [ 40,  88, 144]],

       [[ 26,  84, 150],
        [ 64, 136, 216]]])

In [39]:
ax*2

array([[[  2,  12,  30],
        [ 16,  40,  72]],

       [[ 14,  48,  90],
        [ 40,  88, 144]],

       [[ 26,  84, 150],
        [ 64, 136, 216]]])

In [40]:
ax/3

array([[[ 0.33333333,  2.        ,  5.        ],
        [ 2.66666667,  6.66666667, 12.        ]],

       [[ 2.33333333,  8.        , 15.        ],
        [ 6.66666667, 14.66666667, 24.        ]],

       [[ 4.33333333, 14.        , 25.        ],
        [10.66666667, 22.66666667, 36.        ]]])

In [41]:
ax//3

array([[[ 0,  2,  5],
        [ 2,  6, 12]],

       [[ 2,  8, 15],
        [ 6, 14, 24]],

       [[ 4, 14, 25],
        [10, 22, 36]]])

In [ ]:
ax%