In [1]:
import numpy as np

In [3]:
oned=np.array([1,3,4])

In [8]:
twod=np.random.randint(10,size=(2,3))

In [9]:
oned

array([1, 3, 4])

In [10]:
twod

array([[7, 6, 1],
       [7, 1, 4]])

In [11]:
threed=np.random.randint(20,size=(3,3,5))

In [12]:
threed

array([[[ 9, 10, 17,  7, 19],
        [ 2, 14, 14, 14, 18],
        [18, 18, 13,  7, 13]],

       [[ 0, 13,  7, 11, 19],
        [16,  5, 14, 12,  5],
        [ 4, 11,  8,  7, 13]],

       [[18, 10, 11,  8,  5],
        [16,  2, 11,  1,  6],
        [10, 11,  0,  6,  2]]])

In [13]:
oned.shape

(3,)

In [14]:
oned=oned.reshape(1,3)

In [15]:
oned.shape

(1, 3)

In [16]:
twod.shape

(2, 3)

In [18]:
threed.shape

(3, 3, 5)

In [19]:
oned.ndim

2

In [20]:
twod.ndim

2

In [21]:
threed.ndim

3

In [22]:
oned.dtype

dtype('int64')

In [23]:
twod.dtype

dtype('int64')

In [24]:
threed.dtype

dtype('int64')

In [25]:
oned.size

3

In [26]:
twod.size

6

In [27]:
threed.size

45

In [28]:
type(oned)

numpy.ndarray

In [29]:
type(twod)

numpy.ndarray

In [30]:
type(threed)

numpy.ndarray

In [31]:
import pandas as pd

In [33]:
dataf=pd.DataFrame(twod,index=["1","2"],columns=["1","2","3"])

In [34]:
dataf

1  2  3
1  7  6  1
2  7  1  4

In [36]:
ones=np.ones((10,2))

In [38]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [40]:
zeroes=np.zeros((7,3,2))

In [41]:
zeroes.astype(int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [42]:
rangee=np.arange(0,100,3)

In [43]:
rangee

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [44]:
rndom=np.random.randint(0,10,size=(4,6))

In [45]:
rndom

array([[3, 7, 2, 8, 4, 5],
       [8, 4, 7, 8, 8, 8],
       [0, 1, 7, 5, 2, 7],
       [5, 2, 2, 7, 0, 8]])

In [51]:
rnf=np.random.random(size=(3,5))

In [52]:
rnf

array([[0.02587656, 0.12214017, 0.78317336, 0.17237228, 0.39425331],
       [0.62477972, 0.61552151, 0.0444381 , 0.43410381, 0.10784855],
       [0.9476657 , 0.89717222, 0.85467947, 0.39724805, 0.60931722]])

In [66]:
np.random.seed(42)

In [67]:
rarray=np.random.randint(10,size=(4,6))

In [68]:
rarray

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [69]:
arr=np.random.randint(1,10,size=(3,7))

In [70]:
arr

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [71]:
np.unique(arr)

array([1, 2, 3, 4, 5, 7, 9])

In [72]:
arr[0]

array([9, 1, 3, 7, 4, 9, 3])

In [73]:
arr[0,0]

9

In [79]:
arr[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [83]:
arr[:2][:2,:2]

array([[9, 1],
       [5, 3]])

In [84]:
first=np.random.randint(10,size=(3,5))

In [88]:
one=np.ones((3,5)).astype(int)

In [89]:
first

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [90]:
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [91]:
add=first+one

In [92]:
add

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [93]:
np.add(first,one)

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [95]:
aone=np.ones((5,3)).astype(int)

In [96]:
aone

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
add+aone

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [101]:
aone=aone.reshape(3,5)

In [102]:
aone

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [108]:
lone=add+aone

In [109]:
none=np.ones((3,5)).astype(int)

In [111]:
none

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [112]:
sub=lone-none

In [113]:
sub

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [114]:
sub*none

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [115]:
mul=sub*none

In [116]:
mul

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [117]:
mul**2

array([[ 49,  64,   9,   1,  16],
       [  4,  64,  16,   4,  36],
       [ 36, 100,  16,  36,   4]])

In [119]:
sq=np.square(mul)

In [120]:
sq.mean

<function ndarray.mean>

In [121]:
sq.mean()

30.333333333333332

In [122]:
np.mean(sq)

30.333333333333332

In [123]:
np.max(sq)

100

In [124]:
np.min(sq)

1

In [125]:
np.std(sq)

27.78168861358543

In [126]:
np.var(sq)

771.8222222222224

In [127]:
sq=sq.reshape(3,5,1)

In [128]:
sq

array([[[ 49],
        [ 64],
        [  9],
        [  1],
        [ 16]],

       [[  4],
        [ 64],
        [ 16],
        [  4],
        [ 36]],

       [[ 36],
        [100],
        [ 16],
        [ 36],
        [  4]]])

In [129]:
sqt=sq.T

In [130]:
sqt

array([[[ 49,   4,  36],
        [ 64,  64, 100],
        [  9,  16,  16],
        [  1,   4,  36],
        [ 16,  36,   4]]])

In [131]:
ran1=np.random.randint(10,size=(3,2))

In [133]:
ran2=np.random.randint(10,size=(3,3))

In [134]:
dotp=np.dot(ran1,ran2)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [135]:
dotp=np.dot(ran2,ran1)

In [136]:
dotp

array([[163,  53],
       [ 94,  55],
       [209,  81]])

In [137]:
ran2.dot(ran1)

array([[163,  53],
       [ 94,  55],
       [209,  81]])

In [138]:
ran1.T.dot(ran2)

array([[144, 155, 155],
       [ 65,  67,  73]])

In [140]:
rn1=np.random.randint(10,size=(3,3))

In [141]:
rn2=np.random.randint(10,size=(3,3))

In [142]:
rn1>rn2

array([[False,  True,  True],
       [ True,  True, False],
       [False,  True, False]])

In [143]:
rn1>=rn2

array([[ True,  True,  True],
       [ True,  True, False],
       [False,  True, False]])

In [144]:
rn1[rn1>7]

array([8, 8])

In [147]:
rn1>7

array([[False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [148]:
rn1==rn2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [149]:
sort(rn1)

NameError: name 'sort' is not defined

In [150]:
rn1.sort()

In [151]:
np.sort(rn1)

array([[0, 6, 8],
       [0, 7, 8],
       [2, 7, 7]])

In [152]:
np.argsort(rn1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [156]:
np.argmax(rn2,0)

array([2, 0, 2])

In [155]:
np.argmin(rn1,1)

array([0, 0, 0])

In [161]:
nor=np.random.normal(1,100,size=(3,3))

In [162]:
nor

array([[ -40.03833087,  118.97163447,  -88.82079395],
       [  84.47954192,   30.65613843, -102.78298765],
       [  -6.5803745 ,   98.29635338,   80.55954639]])

In [165]:
even=np.arange(1,100,2)

In [166]:
even

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])