In [1]:
import numpy as np

In [2]:
a1=np.array([1,4,5])

In [3]:
a1

array([1, 4, 5])

In [4]:
a2=np.array([[1,3,5],[2,4,6]])

In [5]:
a2

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [15]:
a1.dtype

dtype('int64')

In [16]:
a2.dtype

dtype('int64')

In [17]:
a1.size

3

In [18]:
a2.size

6

In [19]:
type(a1)

numpy.ndarray

In [20]:
import pandas as pd