In [1]:
import numpy as np

In [5]:
arra=np.random.randint(2,333,(5,5))

In [6]:
arra

array([[300,  57, 204, 239, 266],
       [ 81, 313, 225, 142, 131],
       [ 20,  56, 170, 144, 294],
       [ 88, 127,  82,   3, 185],
       [ 45, 324, 163, 322, 227]])

In [7]:
np.unique(arra)

array([  3,  20,  45,  56,  57,  81,  82,  88, 127, 131, 142, 144, 163,
       170, 185, 204, 225, 227, 239, 266, 294, 300, 313, 322, 324])

In [9]:
%run 'creating numpy array.ipynb'

In [10]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a3

NameError: name 'a3' is not defined

In [13]:
%run 'Numpy intro.ipynb'

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a3[0][0]

array([1, 2, 3])

In [17]:
a3[0][0][1]

2

In [32]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [51]:
a4=np.random.randint(0,10,(2,4,3,2,4,5))

In [52]:
a4

array([[[[[[1, 9, 6, 8, 7],
           [5, 5, 6, 1, 9],
           [4, 0, 2, 0, 6],
           [8, 7, 9, 9, 3]],

          [[2, 2, 1, 9, 4],
           [2, 8, 5, 0, 5],
           [1, 2, 7, 0, 6],
           [1, 5, 8, 9, 8]]],


         [[[6, 4, 8, 4, 6],
           [4, 3, 6, 3, 4],
           [1, 7, 7, 1, 2],
           [0, 7, 4, 3, 7]],

          [[6, 2, 7, 9, 4],
           [6, 3, 1, 2, 7],
           [1, 5, 2, 5, 5],
           [5, 1, 3, 5, 9]]],


         [[[4, 5, 7, 1, 2],
           [6, 1, 9, 2, 5],
           [9, 8, 6, 8, 9],
           [4, 2, 4, 1, 9]],

          [[8, 0, 4, 8, 4],
           [5, 8, 1, 5, 1],
           [4, 9, 8, 5, 6],
           [3, 7, 0, 1, 4]]]],



        [[[[4, 6, 2, 2, 6],
           [5, 3, 4, 6, 4],
           [2, 0, 0, 7, 3],
           [7, 0, 8, 3, 7]],

          [[9, 9, 4, 7, 0],
           [0, 6, 0, 5, 8],
           [0, 4, 0, 6, 3],
           [1, 2, 6, 2, 3]]],


         [[[6, 3, 8, 2, 8],
           [4, 1, 2, 2, 2],
           [9, 4, 1, 6

In [63]:
a4[0][2][1][1][1][2]

0

In [65]:
a4[:,:1,:,:,:1,:3]

array([[[[[[1, 9, 6]],

          [[2, 2, 1]]],


         [[[6, 4, 8]],

          [[6, 2, 7]]],


         [[[4, 5, 7]],

          [[8, 0, 4]]]]],




       [[[[[0, 8, 6]],

          [[1, 0, 5]]],


         [[[0, 5, 7]],

          [[2, 8, 3]]],


         [[[8, 2, 8]],

          [[1, 2, 4]]]]]])